name: epub_decoder
description: Flutter Package to parse EPUB files (EBooks), with support for Media Overlays!
version: 0.1.4
repository: https://github.com/SofieTorch/epub_decoder

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: ">=1.17.0"

topics:
  - epub
  - ebook
  - reader
  - mediaoverlays

dependencies:
  archive: ^4.0.7
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  mockito: ^5.4.4
  build_runner: ^2.4.11

